Add decrement button for count
TahsinAyman/counter-ts-react pull request #1
Opened 2023-11-12 14:54 UTC by TahsinAyman

This pull request adds a decrement button for the count in the App component. Users can now decrease the count by clicking on the "-" button. This feature enhances the functionality of the app and provides a better user experience.

No issues were fixed in this pull request.

2023-11-12 15:31 UTC, fullstackltd submitted a review, later dismissed
You have a tiger

2023-11-14 03:47 UTC, fullstackltd requested changes
please see the comments on the code

2023-11-14 03:47 UTC, fullstackltd commented on src/App.tsx
> +        </button>
Change the text to "Decrement'

2023-11-14 03:56 UTC, TahsinAyman commented on src/App.tsx
> +        </button>
done working on it

2023-11-14 03:57 UTC, fullstackltd approved these changes
well done

2023-11-14 03:58 UTC, merged